version: 1

models:
  - name: staging_briefings
    columns:
      - name: RowNumber
        data_type: string
        tests:
          - assert_column_type:
              column_type: string
      - name: EntradaUnica
        data_type: STRING
      - name: CanalPerfil
        data_type: STRING
      - name: Ano
        data_type: STRING
      - name: Mes
        data_type: STRING
      - name: Briefing
        data_type: STRING
      - name: Account_Manager
        data_type: STRING
      - name: Cupom_divulgado_no_ms
        data_type: STRING
      - name: Link_divulgado_no_ms
        data_type: STRING
      - name: Data_de_envio
        data_type: STRING
      - name: Comentrios_do_AM
        data_type: STRING
      - name: Tipo_de_briefing
        data_type: STRING
      - name: Flag_Email_Enviado
        data_type: STRING
      - name: emailprincipal
        data_type: STRING
      - name: emailsecundario
        data_type: STRING
      - name: emailam
        data_type: STRING
      - name: creatorname
        data_type: STRING
      - name: canal
        data_type: STRING
      - name: amatualizado
        data_type: STRING